repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: check-toml
- repo: https://github.com/rust-lang/rustfmt
  rev: stable
  hooks:
    - id: rustfmt
- repo: https://github.com/doublify/pre-commit-rust
  rev: master
  hooks:
    - id: clippy
      args: [--all-features, --all-targets, -- -D warnings]
    - id: cargo-check
    - id: cargo-test
